version: "3.9"
services:
  api:
    image: ${DOCKER_REPO}:${DOCKER_TAG}
    init: true
    ports:
      - "80:8080"
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - API_URL
      - PORT
      - AWS_COGNITO_POOL_ID
      - AWS_COGNITO_CLIENT_ID